--!strict
--// config \\--
return table.freeze({
	AFKZone1 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 1,
	}),
	AFKZone2 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 2,
	}),
	AFKZone3 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 2.5,
	}),
	AFKZone4 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 3,
	}),
	AFKZone5 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 3.5,
	}),
	AFKZone6 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 4,
	}),
	AFKZone7 = table.freeze({
		TickRate = 1,
		BaseGain = 1,
		ZoneMultiplier = 4.5,
		PassKey = "PremiumZone",
	}),
})
